version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: Afo
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    networks:
      - pillfindr
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: test_db
    networks:
      - pillfindr
networks:
  pillfindr: